from .Options import Options as _Options
from typing   import Union

import threading
import tkinter as tk

class Interface(threading.Thread):
    Config:                                         Union[tk.Frame, tk.LabelFrame, tk.Label, None]

    def __init__(self, options: _Options)           -> None:...
    def run(self)                                   -> None:...
    def _scroll_bar(self)                           -> None:...
    def stop(self)                                  -> None:...
    def add_bot(self)                               -> None:...
    def add_bot_add(self)                           -> None:...
    def add_bot_cancel(self)                        -> None:...
    def UpDate_Bot(self, Id: str)                   -> None:...
    def change_language(self)                       -> None:...
    def change_language_save(self, event: tk.Event) -> None:...
    def cancel(self)                                -> None:...
    def Start(self)                                 -> None:...
    def Menu(self, main: tk.Tk)                     -> tk.Menu:...
    def Bots(self)                                  -> Union[None, bool]:...


class BotConfig(object):
    def __init__(self, main: Interface, Bot: None, options: _Options) -> None:...
    def Config(self)                                                  -> None:...
    def Sup_Bot(self)                                                 -> None:...
    def _Main(self)                                                   -> None:...
    def Prefix(self)                                                  -> None:...
    def Owner(self)                                                   -> None:...
    def New_prefix(self)                                              -> None:...
    def Sup_Prefix(self)                                              -> None:...
    def New(self)                                                     -> None:...
    def New_owner(self)                                               -> None:...
    def Sup_owner(self)                                               -> None:...
    def New_o(self)                                                   -> None:...
    def Stop(self)                                                    -> None:...
    def Start(self)                                                   -> None:...
    def del_(self)                                                    -> bool:...
    def Input(self, text: str, text_2: str, command)                  -> tk.Frame:...