from .Bot import Bot as _Bot

import threading

class Loop:
    def __init__(self, Bot: _Bot) -> None:...
    def start(self)               -> bool:...
    def stop(self)                -> bool:...

class _Loop(threading.Thread):
    def __init__(self, Bot: _Bot) -> None:...
    def run(self)                 -> None:...
    def _await(self, coro)        -> None:...
    def loop(self)                -> None:...