from typing   import Union

try:
    import discord
    from discord.ext import commands
except Exception:
    raise

class _MissingSentinel:...
MISSING = _MissingSentinel()

def Save(path: str = MISSING, obj: dict = MISSING)                                                                             -> bool:...
def Open(path: str = MISSING, __defalts: dict = {})                                                                            -> dict:...
def _to_str(size: int, suffixes: tuple, base: int, *, precision: int = 1, separator: str = " ")                                -> str:...
def decimal(size: int, *, precision: int = 1, separator: str = " ")                                                            -> str:...
async def send(ctx: commands.Context = MISSING, *, message: str = False, embed: discord.Embed = False, reference: bool = True) -> Union[discord.Message, discord.Embed, bool]:...
async def purge(ctx: commands.Context = MISSING, nombre: int = MISSING)                                                        -> Union[bool, list[discord.Message]]:...
async def channel_send(channel: discord.TextChannel = MISSING, *, message: str = False, embed: discord.Embed = False)          -> Union[discord.Message, discord.Embed, bool]:...