from .Bot        import Bot as _Bot
from .YTDLSource import YTDLSource
from typing      import Union
from discord.ext import commands

import discord

class Song:
    __slots__: tuple

    def __init__(self, source: YTDLSource)                                     -> None:...
    def create_embed(self, user_id: int)                                       -> discord.Embed:...

class VoiceState:
    is_playing: bool
    def __init__(self, Bot: _Bot, ctx: commands.Context)                       -> None:...
    async def _audio_task(self)                                                -> None:...
    async def __stop(self)                                                     -> None:...
    async def _play(self, ctx: commands.Context, search: str)                  -> None:...
    async def _playlist(self, ctx: commands.Context, data: dict)               -> None:...
    async def _video_by_name(self, ctx: commands.Context, data: dict)          -> None:...
    async def _stop(self)                                                      -> None:...
    async def _queue(self, ctx: commands.Context, page: int)                   -> None:...
    async def _skip(self, ctx: commands.Context)                               -> None:...
    async def _volume(self, ctx: commands.Context, volume: Union[float, bool]) -> None:...
    async def _pause(self)                                                     -> None:...
    async def _resume(self)                                                    -> None:...
    async def _shuffle(self)                                                   -> None:...
    async def _remove(self, ctx: commands.Context, index: int)                 -> None:...
    async def _leave(self)                                                     -> bool:...
    async def _loop(self)                                                      -> bool:...
    async def _join(self, ctx: commands.Context)                               -> bool:...
    async def _get_current(self)                                               -> Union[Song, YTDLSource]:...